-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

BEGIN;

INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('teacher', 'Stevie', 'Hawking','hawking@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('teacher', 'Elon', 'Musk','musk@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('teacher', 'Tut', 'Common','common@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('teacher', 'Elmer', 'Fudd','fudd@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('teacher', 'Brian', 'Cerny','cerney@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');

INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('student', 'Bart', 'Frampton','frampton@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('student', 'Michael', 'Simpson','simpson@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('student', 'Ryan', 'Jackson','jackson@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('student', 'George', 'Gosling','gosling@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
INSERT INTO users (userType, firstName, lastName, email, salt, password) VALUES ('student', 'Peter', 'Bush','bush@gmail.com', 'a5ovqz02NeLR963sLDKVQ5DJ79p1x4YRa/RTjtsX6iIukUknFLUg/kehZCklFFkNaLHD8ac5EwJ92rPyfH+91hG+x8+XkRUl9mSLrRrhusJekcL/+OH5jKUL6NanbQcIOJ639+dwlIJSmFhLbayWJpBObt+Ogv76V+SwxH/0fmo=', 'ubwMT/KWFtKP7LCRfI0UZA==');
	
INSERT INTO courses (name, capacity, fee, startDate, endDate, teacherId, subject, difficulty, description) VALUES ('Quantam Bananas', 30, 99.99, '2017-05-04', '2017-07-10', 1, 'Physics', 'advanced', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sollicitudin ante non accumsan tincidunt. Integer scelerisque sagittis enim, fermentum congue purus egestas a. In hac habitasse platea dictumst. Proin pharetra est neque, eu faucibus arcu euismod eget. Nulla tincidunt, diam id vehicula interdum, quam lacus molestie tellus, sed tempus nibh nulla at velit. Sed facilisis turpis quis metus pellentesque, a laoreet odio ullamcorper. Pellentesque fermentum lectus nec mauris gravida mattis vel ut nibh. Proin porttitor nisi metus. Nunc blandit felis pretium, interdum mi eget, tempor ex. Donec velit neque, pellentesque sit amet interdum a, interdum vitae elit. Fusce vel leo ullamcorper, volutpat mauris eleifend, rutrum lacus.');
INSERT INTO courses (name, capacity, fee, startDate, endDate, teacherId, subject, difficulty, description) VALUES ('How to Shock People with your Tesla', 20, 60, '2017-05-14', '2017-07-14', 2, 'Engineering', 'intermediate', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum nulla in odio rutrum, ut interdum lacus suscipit. Fusce et lorem eget lacus finibus rhoncus. Pellentesque mattis justo a sapien tincidunt tincidunt. Mauris a nisl sollicitudin, accumsan enim non, vestibulum lacus. Vestibulum quis tempus dui, sit amet dapibus enim. Aenean quis ligula suscipit est laoreet sollicitudin. Donec varius felis eget tortor ultrices lacinia. Suspendisse consectetur, metus ut tempor varius, ante magna consectetur quam, eget accumsan velit mauris ut nisl. Donec dapibus metus nulla, vitae molestie tellus dignissim at. Integer ullamcorper faucibus mollis.');
INSERT INTO courses (name, capacity, fee, startDate, endDate, teacherId, subject, difficulty, description) VALUES ('Photography for Mummies', 15, 25, '2017-06-01', '2017-06-30', 3, 'Time Wasting', 'intermediate', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mi elit, consequat non pulvinar a, porttitor et ipsum. Proin ultricies non tortor non condimentum. Donec porta felis eget tellus consectetur pellentesque. Nulla ullamcorper, justo eget congue facilisis, purus quam elementum elit, eget luctus sapien mauris quis tellus. Aliquam vel eros sed enim commodo congue et et diam. Aliquam mattis, massa eu interdum faucibus, nibh felis pulvinar risus, id iaculis urna orci sit amet sem. Vestibulum pellentesque felis tellus, ac tempor lorem lacinia vel. Vestibulum eget orci nunc. Sed eget dolor ac eros sagittis condimentum nec non orci. Duis ultricies lectus vel neque tincidunt ornare. Integer venenatis viverra justo, ut hendrerit mauris tincidunt sit amet. Nunc hendrerit lectus eget est tempor finibus. Donec convallis, eros congue convallis congue, lorem tortor tristique dui, et semper nisi velit ut ipsum. Suspendisse aliquam magna nec faucibus sollicitudin. Cras metus lacus, bibendum at dui eu, mattis blandit diam.');
INSERT INTO courses (name, capacity, fee, startDate, endDate, teacherId, subject, difficulty, description) VALUES ('Killing Wabbits', 10, 0, '2017-06-14', '2017-08-15', 4, 'Athletics', 'beginner', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend sodales ullamcorper. Phasellus blandit elit eget congue tincidunt. Donec vitae nisi imperdiet, dictum risus interdum, convallis lorem. Phasellus efficitur sit amet tellus vitae aliquam. Duis malesuada leo ac massa suscipit sodales. Nulla ut rutrum tortor. Nulla ligula ipsum, porta quis tempus ut, laoreet et tortor. Maecenas a erat nulla. Morbi porttitor, justo porta sodales accumsan, urna risus vulputate elit, nec blandit tellus felis eget dui. Donec iaculis diam a nulla convallis, a bibendum felis finibus. Nunc finibus suscipit tortor sit amet vestibulum. Quisque fringilla in enim sit amet interdum. Nullam viverra tincidunt augue, eget sollicitudin ipsum gravida eu. Quisque ac massa arcu.');
INSERT INTO courses (name, capacity, fee, startDate, endDate, teacherId, subject, difficulty, description) VALUES ('Guitar Acchordingly', 20, 149.95, '2017-04-26', '2017-07-20', 5, 'Music', 'beginner', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec quam aliquet, imperdiet nisi in, porttitor felis. Morbi finibus velit sed lorem rhoncus porta vel eu turpis. Nunc malesuada erat ut luctus congue. In eu tortor et odio vulputate auctor. Sed in justo porttitor leo imperdiet mollis. Aliquam accumsan, lectus vel imperdiet lobortis, sem nisl sodales ligula, ac varius erat neque vulputate massa. Duis sit amet magna sed felis imperdiet convallis.');

INSERT INTO student_course (studentId, courseId) VALUES (1,1);
INSERT INTO student_course (studentId, courseId) VALUES (1,2);
INSERT INTO student_course (studentId, courseId) VALUES (1,5);

INSERT INTO student_course (studentId, courseId) VALUES (2,2);
INSERT INTO student_course (studentId, courseId) VALUES (2,3);
INSERT INTO student_course (studentId, courseId) VALUES (2,4);
INSERT INTO student_course (studentId, courseId) VALUES (2,5);

INSERT INTO student_course (studentId, courseId) VALUES (3,1);
INSERT INTO student_course (studentId, courseId) VALUES (3,4);

INSERT INTO student_course (studentId, courseId) VALUES (4,1);
INSERT INTO student_course (studentId, courseId) VALUES (4,2);
INSERT INTO student_course (studentId, courseId) VALUES (4,3);
INSERT INTO student_course (studentId, courseId) VALUES (4,4);
INSERT INTO student_course (studentId, courseId) VALUES (4,5);

INSERT INTO student_course (studentId, courseId) VALUES (5,1);
INSERT INTO student_course (studentId, courseId) VALUES (5,2);
INSERT INTO student_course (studentId, courseId) VALUES (5,4);


COMMIT;